// Generated using prebuild.py
using System.Collections.Generic;
namespace CoDArchipelago{
static class Data{
public static readonly Dictionary<string, string> pickupLocations = new(){
{"LOCATION_ITEM_FISH_FOOD", "Lostleaf Lake - Treehouse Fish Food"},
{"LOCATION_ITEM_PRINCESS_1", "Lady Opal's Egg: Castle"},
{"LOCATION_ITEM_PRINCESS_2", "Lady Opal's Egg: Pool"},
{"LOCATION_ITEM_PRINCESS_3", "Lady Opal's Egg: Poki-Poki"},
};
public static readonly Dictionary<string, string> eventLocations = new(){
{"LOCATION_CAVE_NURIKABE_FALLEN", "Beat Mighty Wall"},
{"LOCATION_GRATITUDE_DOOR1", "Moon Cavern Heart Door"},
{"LOCATION_MONSTER_LOBBY_PIPES_RISEN", "Armada Lobby Purple Valve"},
{"LOCATION_MONSTER_LOBBY_STEAM", "Armada Lobby Green Valve"},
{"LOCATION_PALACE_LOBBY_FAUCET_ON", "Prismic Palace Lobby Faucet Preston"},
{"LOCATION_CAVE_GALLERY_LOBBY_TORCH_EXTINGUISH", "Gallery Lobby - Extinguish Torches"},
{"LOCATION_LAKE_SWINGS_RAISED", "Lostleaf Lake - Preston Near Treehouse"},
{"LOCATION_LAKE_KAPPA_SUCCESS", "Lostleaf Lake - Help Shelnert"},
{"LOCATION_LAKE_CRYPT_GATE_OPEN", "Lostleaf Lake - Back of the Headstone"},
{"LOCATION_LAKE_BELL_RANG", "Lostleaf Lake - Ring Bell"},
{"LOCATION_LAKE_CHURCH_SUCCESS", "Lostleaf Lake - Angel Statue Puzzle"},
{"LOCATION_MONSTER_BOILS_REMOVED", "Airborne Armada - Help Mr. Kerrington"},
{"LOCATION_PALACE_ABYSS_HOOP_SUCCESS", "Prismic Palace - Basement Star Hoops"},
{"LOCATION_PALACE_LAKE_GATE_OPEN", "Prismic-Lostleaf Connector - Preston"},
{"LOCATION_PALACE_GATE_RISEN", "Prismic Palace - Angel Statue Puzzle"},
{"LOCATION_PALACE_MELTED_ICE", "Prismic Palace - Help Lady Opal"},
{"LOCATION_PALACE_SENTRIES_DISABLED", "Prismic Palace - Sentry Control Preston"},
{"LOCATION_PALACE_SANCTUM_RACE_FINISHED", "Prismic Palace - Heaven's Path Race"},
{"LOCATION_GALLERY_SAGE_PAINTING_SUCCESS", "Gallery of Nightmares - Sage's Painting"},
{"LOCATION_GALLERY_MONSTER_PAINTING_SUCCESS", "Gallery of Nightmares - Mr. Kerrington's Painting"},
{"LOCATION_GALLERY_KAPPA_PAINTING_SUCCESS", "Gallery of Nightmares - Shelnert's Painting"},
{"LOCATION_GALLERY_MONSTER_SHORTCUT_OPEN", "Gallery-Armada Connector - Preston"},
{"LOCATION_GALLERY_STATUE_PUZZLE_SUCCESS", "Gallery of Nightmares - Swamp Angel Statue Puzzle"},
{"LOCATION_GALLERY_ANGEL_STATUE_SHADOWS_SUCCESS", "Gallery of Nightmares - Sewer Angel Statue Puzzle"},
{"LOCATION_GALLERY_PRINCESS_PAINTING_SUCCESS", "Gallery of Nightmares - Lady Opal's Painting"},
};
public static readonly Dictionary<string, string> cardLocations = new(){
{"LOCATION_CARD_CAVE_MUSHROOM", "Card: Sun Cavern - Air Vent"},
{"LOCATION_CARD_CAVE_NURIKABE", "Card: Lostleaf Lobby - Branches"},
{"LOCATION_CARD_CAVE_KOI_CAVE", "Card: Moon Cavern - Statue"},
{"LOCATION_CARD_CAVE_SWITCH", "Card: Armada Lobby - Jester Boots"},
{"LOCATION_CARD_CAVE_SHOOTING_STAR", "Card: Moon Cavern - Dive"},
{"LOCATION_CARD_CAVE_HUNGER", "Card: Gallery Lobby - Hedge Maze"},
{"LOCATION_CARD_LAKE_KAPPA", "Card: Lostleaf Lake - Teepee"},
{"LOCATION_CARD_LAKE_CRYPT", "Card: Lostleaf Lake - Apple Tree"},
{"LOCATION_CARD_LAKE_KOI", "Card: Lostleaf Lake - Lake Stump"},
{"LOCATION_CARD_LAKE_SUN", "Card: Lostleaf Lake - Church"},
{"LOCATION_CARD_LAKE_SAPLING", "Card: Lostleaf Lake - Entry"},
{"LOCATION_CARD_LAKE_GROVE", "Card: Lostleaf Lake - Treehouse"},
{"LOCATION_CARD_MONSTER_MONSTER", "Card: Airborne Armada - Slide"},
{"LOCATION_CARD_MONSTER_SPIN_BLADE", "Card: Airborne Armada - Pipe"},
{"LOCATION_CARD_MONSTER_BOIL", "Card: Airborne Armada - Broken Wing"},
{"LOCATION_CARD_MONSTER_DUMPLING", "Card: Airborne Armada - Behind Entry Drone"},
{"LOCATION_CARD_MONSTER_FISH", "Card: Airborne Armada - Hammocks"},
{"LOCATION_CARD_MONSTER_FF", "Card: Airborne Armada - Heart"},
{"LOCATION_CARD_PALACE_PRINCESS", "Card: Prismic Palace - Observatory"},
{"LOCATION_CARD_PALACE_URCHIN", "Card: Prismic Palace - Top of Observatory"},
{"LOCATION_CARD_PALACE_PALM_TREE_FLOAT", "Card: Prismic Palace - Snowcastle"},
{"LOCATION_CARD_PALACE_SEASTAR", "Card: Prismic Palace - Top of Palace"},
{"LOCATION_CARD_PALACE_MORAY", "Card: Prismic Palace - Above Pool"},
{"LOCATION_CARD_PALACE_SENTRY", "Card: Prismic Palace - Inside Palace"},
{"LOCATION_CARD_GALLERY_RATTLES", "Card: Gallery of Nightmares - Swamp Castle"},
{"LOCATION_CARD_GALLERY_GIANT", "Card: Gallery of Nightmares - Sewer Bottom"},
{"LOCATION_CARD_GALLERY_MIMIC_PAINTING", "Card: Gallery of Nightmares - Basement Entrance"},
{"LOCATION_CARD_GALLERY_UNDEAD", "Card: Gallery of Nightmares - Swamp"},
{"LOCATION_CARD_GALLERY_FIRE_SNAKE", "Card: Gallery of Nightmares - Frying Pans"},
{"LOCATION_CARD_GALLERY_CHOMP", "Card: Gallery of Nightmares - Above Pits of Despair Painting"},
{"LOCATION_CARD_CAVE_DRAGON", "Card: Armada-Gallery Connector - Armada Side"},
{"LOCATION_CARD_CAVE_FELLA", "Card: Armada-Gallery Connector - Gallery Side"},
{"LOCATION_CARD_CAVE_SAGE", "Card: Dreams - Top"},
{"LOCATION_CARD_CAVE_VILLAIN", "Card: Gallery Lobby - Behind the Gallery"},
{"LOCATION_CARD_CAVE_PANDORA", "Card: Prismic Palace - Frozen Dining Room"},
{"LOCATION_CARD_CAVE_KING", "Card: Prismic Lobby - Top"},
};
public static readonly Dictionary<string, string> eggLocations = new(){
{"LOCATION_FELLA_CAVE1", "Egg: Sun Cavern - Mighty Wall"},
{"LOCATION_FELLA_CAVE2", "Egg: Sun Cavern - Waterfall"},
{"LOCATION_FELLA_CAVE3", "Egg: Moon Cavern - Dive Puzzle"},
{"LOCATION_FELLA_CAVE4", "Egg: Moon Cavern - Keehee Climb"},
{"LOCATION_FELLA_CAVE5", "Egg: Lostleaf Lobby - Branches"},
{"LOCATION_FELLA_CAVE6", "Egg: Armada Lobby - Cannon"},
{"LOCATION_FELLA_CAVE7", "Egg: Palace Lobby - Submerged"},
{"LOCATION_FELLA_CAVE8", "Egg: Gallery Lobby - Lostleaf Lobby Entry"},
{"LOCATION_FELLA_LAKE1", "Egg: Lostleaf Lake - Entry Stump"},
{"LOCATION_FELLA_LAKE2", "Egg: Lostleaf Lake - Jester Boots"},
{"LOCATION_FELLA_LAKE3", "Egg: Lostleaf Lake - Lake Log"},
{"LOCATION_FELLA_LAKE4", "Egg: Lostleaf Lake - Waterfall"},
{"LOCATION_FELLA_LAKE5", "Egg: Lostleaf Lake - Crypt"},
{"LOCATION_FELLA_LAKE6", "Egg: Lostleaf Lake - Deep Woods Puzzle"},
{"LOCATION_FELLA_LAKE7", "Egg: Lostleaf Lake - Treehouse"},
{"LOCATION_FELLA_LAKE8", "Egg: Lostleaf Lake - Church"},
{"LOCATION_FELLA_MONSTER1", "Egg: Airborne Armada - Tail"},
{"LOCATION_FELLA_MONSTER2", "Egg: Airborne Armada - Burning"},
{"LOCATION_FELLA_MONSTER3", "Egg: Airborne Armada - Slide"},
{"LOCATION_FELLA_MONSTER4", "Egg: Airborne Armada - Dog Food"},
{"LOCATION_FELLA_MONSTER5", "Egg: Airborne Armada - Boiler"},
{"LOCATION_FELLA_MONSTER6", "Egg: Airborne Armada - Pipe"},
{"LOCATION_FELLA_MONSTER7", "Egg: Airborne Armada - Heart"},
{"LOCATION_FELLA_MONSTER8", "Egg: Airborne Armada - Dumpling"},
{"LOCATION_FELLA_PALACE1", "Egg: Prismic Palace - Snowcastle"},
{"LOCATION_FELLA_PALACE2", "Egg: Prismic Palace - Frozen Dining Room"},
{"LOCATION_FELLA_PALACE3", "Egg: Prismic Palace - Inside Observatory"},
{"LOCATION_FELLA_PALACE4", "Egg: Prismic Palace - Observatory Slide"},
{"LOCATION_FELLA_PALACE5", "Egg: Prismic Palace - Bigstar"},
{"LOCATION_FELLA_PALACE6", "Egg: Prismic Palace - Top"},
{"LOCATION_FELLA_PALACE7", "Egg: Prismic Palace - Basement"},
{"LOCATION_FELLA_PALACE8", "Egg: Prismic Palace - Gobbler"},
{"LOCATION_FELLA_CHALICE1", "Egg: Coils of Agony"},
{"LOCATION_FELLA_DROWN1", "Egg: Pits of Despair"},
{"LOCATION_FELLA_UNDEAD1", "Egg: Wastes of Eternity"},
{"LOCATION_FELLA_GALLERY1", "Egg: Gallery of Nightmares - Matryoshka Egg"},
{"LOCATION_FELLA_GALLERY2", "Egg: Gallery of Nightmares - Skull's Eye"},
{"LOCATION_FELLA_GALLERY3", "Egg: Gallery of Nightmares - Mr. Kerrington Painting"},
{"LOCATION_FELLA_GALLERY4", "Egg: Gallery of Nightmares - Sewer"},
{"LOCATION_FELLA_GALLERY5", "Egg: Gallery of Nightmares - Deepest Darkness"},
};
public static readonly Dictionary<string, string> shroomLocations = new(){
{"LOCATION_NOTE_CAVE2", "Shroom: Sun Cavern - Mighty Wall Ground 1"},
{"LOCATION_NOTE_CAVE3", "Shroom: Sun Cavern - Mighty Wall Ground 2"},
{"LOCATION_NOTE_CAVE4", "Shroom: Sun Cavern - Mighty Wall Ground 3"},
{"LOCATION_NOTE_CAVE5", "Shroom: Sun Cavern - Mighty Wall Ground 4"},
{"LOCATION_NOTE_CAVE1", "Shroom: Sun Cavern - Mighty Wall Egg Ledge 1"},
{"LOCATION_NOTE_CAVE6", "Shroom: Sun Cavern - Mighty Wall Egg Ledge 2"},
{"LOCATION_NOTE_CAVE7", "Shroom: Sun Cavern - Mighty Wall Egg Ledge 3"},
{"LOCATION_NOTE_CAVE8", "Shroom: Sun Cavern - High Jump Ledge 1"},
{"LOCATION_NOTE_CAVE9", "Shroom: Sun Cavern - High Jump Ledge 2"},
{"LOCATION_NOTE_CAVE10", "Shroom: Sun Cavern - Tail Spin Ledge 1"},
{"LOCATION_NOTE_CAVE11", "Shroom: Sun Cavern - Tail Spin Ledge 2"},
{"LOCATION_NOTE_CAVE12", "Shroom: Sun Cavern - Ducklings Ledge 1"},
{"LOCATION_NOTE_CAVE13", "Shroom: Sun Cavern - Ducklings Ledge 2"},
{"LOCATION_NOTE_CAVE14", "Shroom: Sun Cavern - Armada Entrance 1"},
{"LOCATION_NOTE_CAVE15", "Shroom: Sun Cavern - Armada Entrance 2"},
{"LOCATION_NOTE_CAVE16", "Shroom: Sun Cavern - Armada Entrance 3"},
{"LOCATION_NOTE_CAVE17", "Shroom: Sun Cavern - Vine Ledge 1"},
{"LOCATION_NOTE_CAVE18", "Shroom: Sun Cavern - Vine Ledge 2"},
{"LOCATION_NOTE_CAVE19", "Shroom: Moon Cavern - Dive Holes 1"},
{"LOCATION_NOTE_CAVE20", "Shroom: Moon Cavern - Dive Holes 2"},
{"LOCATION_NOTE_CAVE21", "Shroom: Moon Cavern - Dive Holes 3"},
{"LOCATION_NOTE_CAVE22", "Shroom: Moon Cavern - Dive Holes 4"},
{"LOCATION_NOTE_CAVE23", "Shroom: Moon Cavern - Dive Holes 5"},
{"LOCATION_NOTE_CAVE24", "Shroom: Moon Cavern - Dive Holes 6"},
{"LOCATION_NOTE_CAVE25", "Shroom: Moon Cavern - Dive Puzzle 1"},
{"LOCATION_NOTE_CAVE26", "Shroom: Moon Cavern - Dive Puzzle 2"},
{"LOCATION_NOTE_CAVE27", "Shroom: Moon Cavern - Dive Puzzle 3"},
{"LOCATION_NOTE_CAVE28", "Shroom: Moon Cavern - Potionfall"},
{"LOCATION_NOTE_CAVE29", "Shroom: Moon Cavern - Lonely Shroom"},
{"LOCATION_NOTE_CAVE30", "Shroom: Moon Cavern - Prismic Pathway 2"},
{"LOCATION_NOTE_CAVE31", "Shroom: Moon Cavern - Prismic Pathway 1"},
{"LOCATION_NOTE_CAVE32", "Shroom: Moon Cavern - Prismic Pathway 3"},
{"LOCATION_NOTE_CAVE33", "Shroom: Moon Cavern - Prismic Statue 1"},
{"LOCATION_NOTE_CAVE34", "Shroom: Moon Cavern - Prismic Statue 2"},
{"LOCATION_NOTE_CAVE35", "Shroom: Moon Cavern - Prismic Entrance 1"},
{"LOCATION_NOTE_CAVE36", "Shroom: Moon Cavern - Prismic Entrance 2"},
{"LOCATION_NOTE_CAVE37", "Shroom: Moon Cavern - Prismic Entrance 3"},
{"LOCATION_NOTE_CAVE38", "Shroom: Moon Cavern - Lava Platforms 1"},
{"LOCATION_NOTE_CAVE39", "Shroom: Moon Cavern - Lava Platforms 2"},
{"LOCATION_NOTE_CAVE40", "Shroom: Moon Cavern - Lava Platforms 3"},
{"LOCATION_NOTE_CAVE41", "Shroom: Moon Cavern - Lava Platforms 4"},
{"LOCATION_NOTE_CAVE42", "Shroom: Moon Cavern - Lava Mushroom Platform 1"},
{"LOCATION_NOTE_CAVE43", "Shroom: Moon Cavern - Lava Mushroom Platform 2"},
{"LOCATION_NOTE_CAVE44", "Shroom: Lostleaf Lobby - Bridge 2"},
{"LOCATION_NOTE_CAVE45", "Shroom: Lostleaf Lobby - Bridge 3"},
{"LOCATION_NOTE_CAVE46", "Shroom: Lostleaf Lobby - Bridge 1"},
{"LOCATION_NOTE_CAVE47", "Shroom: Lostleaf Lobby - Trees 1"},
{"LOCATION_NOTE_CAVE48", "Shroom: Lostleaf Lobby - Trees 2"},
{"LOCATION_NOTE_CAVE49", "Shroom: Lostleaf Lobby - Trees 3"},
{"LOCATION_NOTE_CAVE50", "Shroom: Armada Lobby - Cliffside 1"},
{"LOCATION_NOTE_CAVE51", "Shroom: Armada Lobby - Cliffside 2"},
{"LOCATION_NOTE_CAVE52", "Shroom: Armada Lobby - Cliffside 4"},
{"LOCATION_NOTE_CAVE53", "Shroom: Armada Lobby - Cliffside 5"},
{"LOCATION_NOTE_CAVE54", "Shroom: Armada Lobby - Cliffside 3"},
{"LOCATION_NOTE_CAVE55", "Shroom: Palace Lobby - Ledges 1"},
{"LOCATION_NOTE_CAVE56", "Shroom: Palace Lobby - Ledges 6"},
{"LOCATION_NOTE_CAVE57", "Shroom: Palace Lobby - Ledges 5"},
{"LOCATION_NOTE_CAVE58", "Shroom: Palace Lobby - Ledges 3"},
{"LOCATION_NOTE_CAVE59", "Shroom: Palace Lobby - Ledges 2"},
{"LOCATION_NOTE_CAVE60", "Shroom: Palace Lobby - Ledges 4"},
{"LOCATION_NOTE_CAVE61", "Shroom: Palace Lobby - Water 1"},
{"LOCATION_NOTE_CAVE62", "Shroom: Palace Lobby - Water 2"},
{"LOCATION_NOTE_CAVE63", "Shroom: Palace Lobby - Water 3"},
{"LOCATION_NOTE_CAVE64", "Shroom: Palace Lobby - Water 5"},
{"LOCATION_NOTE_CAVE65", "Shroom: Palace Lobby - Water 6"},
{"LOCATION_NOTE_CAVE66", "Shroom: Palace Lobby - Water 4"},
{"LOCATION_NOTE_CAVE67", "Shroom: Gallery Lobby - Fountain 1"},
{"LOCATION_NOTE_CAVE68", "Shroom: Gallery Lobby - Fountain 2"},
{"LOCATION_NOTE_CAVE69", "Shroom: Gallery Lobby - Fountain 3"},
{"LOCATION_NOTE_CAVE70", "Shroom: Gallery Lobby - Fountain 4"},
{"LOCATION_NOTE_CAVE71", "Shroom: Gallery Lobby - Castle Hill 3"},
{"LOCATION_NOTE_CAVE72", "Shroom: Gallery Lobby - Castle Hill 5"},
{"LOCATION_NOTE_CAVE73", "Shroom: Gallery Lobby - Castle Hill 4"},
{"LOCATION_NOTE_CAVE74", "Shroom: Gallery Lobby - Castle Hill 1"},
{"LOCATION_NOTE_CAVE75", "Shroom: Gallery Lobby - Castle Hill 2"},
{"LOCATION_NOTE_CAVE76", "Shroom: Gallery Lobby - Entryway 1"},
{"LOCATION_NOTE_CAVE77", "Shroom: Gallery Lobby - Entryway 4"},
{"LOCATION_NOTE_CAVE78", "Shroom: Gallery Lobby - Entryway 5"},
{"LOCATION_NOTE_CAVE79", "Shroom: Gallery Lobby - Entryway 3"},
{"LOCATION_NOTE_CAVE80", "Shroom: Gallery Lobby - Entryway 2"},
{"LOCATION_NOTE_LAKE1", "Shroom: Lostleaf Lake - Treehouse Branches 4"},
{"LOCATION_NOTE_LAKE2", "Shroom: Lostleaf Lake - Treehouse Branches 3"},
{"LOCATION_NOTE_LAKE3", "Shroom: Lostleaf Lake - Treehouse Branches 1"},
{"LOCATION_NOTE_LAKE4", "Shroom: Lostleaf Lake - Treehouse Branches 2"},
{"LOCATION_NOTE_LAKE5", "Shroom: Lostleaf Lake - Treehouse Branches 6"},
{"LOCATION_NOTE_LAKE6", "Shroom: Lostleaf Lake - Treehouse Branches 5"},
{"LOCATION_NOTE_LAKE7", "Shroom: Lostleaf Lake - Deep Woods 2"},
{"LOCATION_NOTE_LAKE8", "Shroom: Lostleaf Lake - Deep Woods 1"},
{"LOCATION_NOTE_LAKE9", "Shroom: Lostleaf Lake - Deep Woods 3"},
{"LOCATION_NOTE_LAKE10", "Shroom: Lostleaf Lake - Deep Woods 6"},
{"LOCATION_NOTE_LAKE11", "Shroom: Lostleaf Lake - Deep Woods 4"},
{"LOCATION_NOTE_LAKE12", "Shroom: Lostleaf Lake - Deep Woods 5"},
{"LOCATION_NOTE_LAKE13", "Shroom: Lostleaf Lake - Behind Church 3"},
{"LOCATION_NOTE_LAKE14", "Shroom: Lostleaf Lake - Behind Church 1"},
{"LOCATION_NOTE_LAKE15", "Shroom: Lostleaf Lake - Behind Church 2"},
{"LOCATION_NOTE_LAKE16", "Shroom: Lostleaf Lake - Teepee 1"},
{"LOCATION_NOTE_LAKE17", "Shroom: Lostleaf Lake - Teepee 3"},
{"LOCATION_NOTE_LAKE18", "Shroom: Lostleaf Lake - Teepee 2"},
{"LOCATION_NOTE_LAKE19", "Shroom: Lostleaf Lake - Waterfall Logs 2"},
{"LOCATION_NOTE_LAKE20", "Shroom: Lostleaf Lake - Waterfall Logs 3"},
{"LOCATION_NOTE_LAKE21", "Shroom: Lostleaf Lake - Waterfall Logs 4"},
{"LOCATION_NOTE_LAKE22", "Shroom: Lostleaf Lake - Waterfall Logs 1"},
{"LOCATION_NOTE_LAKE23", "Shroom: Lostleaf Lake - Lake Logs 2"},
{"LOCATION_NOTE_LAKE24", "Shroom: Lostleaf Lake - Lake Logs 1"},
{"LOCATION_NOTE_LAKE25", "Shroom: Lostleaf Lake - Lake Logs 3"},
{"LOCATION_NOTE_LAKE26", "Shroom: Lostleaf Lake - Lake Logs 4"},
{"LOCATION_NOTE_LAKE27", "Shroom: Lostleaf Lake - Winky Bouncy Mushroom 1"},
{"LOCATION_NOTE_LAKE28", "Shroom: Lostleaf Lake - Winky Bouncy Mushroom 2"},
{"LOCATION_NOTE_LAKE29", "Shroom: Lostleaf Lake - Winky Bouncy Mushroom 3"},
{"LOCATION_NOTE_LAKE30", "Shroom: Lostleaf Lake - Ramp to Winky Tree 1"},
{"LOCATION_NOTE_LAKE31", "Shroom: Lostleaf Lake - Ramp to Winky Tree 3"},
{"LOCATION_NOTE_LAKE32", "Shroom: Lostleaf Lake - Ramp to Winky Tree 5"},
{"LOCATION_NOTE_LAKE33", "Shroom: Lostleaf Lake - Ramp to Winky Tree 2"},
{"LOCATION_NOTE_LAKE34", "Shroom: Lostleaf Lake - Ramp to Winky Tree 4"},
{"LOCATION_NOTE_LAKE35", "Shroom: Lostleaf Lake - Deep Woods Entryway 1"},
{"LOCATION_NOTE_LAKE36", "Shroom: Lostleaf Lake - Deep Woods Entryway 2"},
{"LOCATION_NOTE_LAKE37", "Shroom: Lostleaf Lake - Deep Woods Entryway 3"},
{"LOCATION_NOTE_LAKE38", "Shroom: Lostleaf Lake - Lake Gravestone 1"},
{"LOCATION_NOTE_LAKE39", "Shroom: Lostleaf Lake - Lake Gravestone 2"},
{"LOCATION_NOTE_LAKE40", "Shroom: Lostleaf Lake - Lake Gravestone 3"},
{"LOCATION_NOTE_LAKE41", "Shroom: Lostleaf Lake - Bridge 2"},
{"LOCATION_NOTE_LAKE42", "Shroom: Lostleaf Lake - Bridge 1"},
{"LOCATION_NOTE_LAKE43", "Shroom: Lostleaf Lake - Bridge 3"},
{"LOCATION_NOTE_LAKE44", "Shroom: Lostleaf Lake - Winky Apple Tree 4"},
{"LOCATION_NOTE_LAKE45", "Shroom: Lostleaf Lake - Winky Apple Tree 3"},
{"LOCATION_NOTE_LAKE46", "Shroom: Lostleaf Lake - Winky Apple Tree 1"},
{"LOCATION_NOTE_LAKE47", "Shroom: Lostleaf Lake - Winky Apple Tree 2"},
{"LOCATION_NOTE_LAKE48", "Shroom: Lostleaf Lake - Church Entryway 3"},
{"LOCATION_NOTE_LAKE49", "Shroom: Lostleaf Lake - Church Entryway 2"},
{"LOCATION_NOTE_LAKE50", "Shroom: Lostleaf Lake - Church Entryway 1"},
{"LOCATION_NOTE_LAKE51", "Shroom: Church - Pews 4"},
{"LOCATION_NOTE_LAKE52", "Shroom: Church - Pews 2"},
{"LOCATION_NOTE_LAKE53", "Shroom: Church - Pews 1"},
{"LOCATION_NOTE_LAKE54", "Shroom: Church - Pews 3"},
{"LOCATION_NOTE_LAKE55", "Shroom: Treehouse - Corners 4"},
{"LOCATION_NOTE_LAKE56", "Shroom: Treehouse - Corners 3"},
{"LOCATION_NOTE_LAKE57", "Shroom: Treehouse - Corners 2"},
{"LOCATION_NOTE_LAKE58", "Shroom: Treehouse - Corners 1"},
{"LOCATION_NOTE_LAKE59", "Shroom: Treehouse - Corners 5"},
{"LOCATION_NOTE_LAKE60", "Shroom: Treehouse - Corners 6"},
{"LOCATION_NOTE_MONSTER1", "Shroom: Airborne Armada - Bouncy Shroom 1"},
{"LOCATION_NOTE_MONSTER2", "Shroom: Airborne Armada - Bouncy Shroom 3"},
{"LOCATION_NOTE_MONSTER3", "Shroom: Airborne Armada - Bouncy Shroom 2"},
{"LOCATION_NOTE_MONSTER4", "Shroom: Airborne Armada - Bouncy Shroom 4"},
{"LOCATION_NOTE_MONSTER5", "Shroom: Airborne Armada - Entry Pathway 5"},
{"LOCATION_NOTE_MONSTER6", "Shroom: Airborne Armada - Front Entrance 1"},
{"LOCATION_NOTE_MONSTER7", "Shroom: Airborne Armada - Front Entrance 2"},
{"LOCATION_NOTE_MONSTER8", "Shroom: Airborne Armada - Front Entrance 3"},
{"LOCATION_NOTE_MONSTER9", "Shroom: Airborne Armada - Side 1"},
{"LOCATION_NOTE_MONSTER10", "Shroom: Airborne Armada - Side 2"},
{"LOCATION_NOTE_MONSTER11", "Shroom: Airborne Armada - Side 3"},
{"LOCATION_NOTE_MONSTER12", "Shroom: Airborne Armada - Back Entrance 1"},
{"LOCATION_NOTE_MONSTER13", "Shroom: Airborne Armada - Back Entrance 2"},
{"LOCATION_NOTE_MONSTER14", "Shroom: Airborne Armada - Back Entrance 3"},
{"LOCATION_NOTE_MONSTER15", "Shroom: Airborne Armada - Back Entrance 4"},
{"LOCATION_NOTE_MONSTER16", "Shroom: Airborne Armada - Back Entrance 6"},
{"LOCATION_NOTE_MONSTER17", "Shroom: Airborne Armada - Back Entrance 5"},
{"LOCATION_NOTE_MONSTER18", "Shroom: Airborne Armada - Topside 1"},
{"LOCATION_NOTE_MONSTER19", "Shroom: Airborne Armada - Topside 2"},
{"LOCATION_NOTE_MONSTER20", "Shroom: Airborne Armada - Topside 3"},
{"LOCATION_NOTE_MONSTER21", "Shroom: Airborne Armada - Entry Pathway 1"},
{"LOCATION_NOTE_MONSTER22", "Shroom: Airborne Armada - Entry Pathway 2"},
{"LOCATION_NOTE_MONSTER23", "Shroom: Airborne Armada - Entry Pathway 3"},
{"LOCATION_NOTE_MONSTER24", "Shroom: Airborne Armada - Entry Pathway 4"},
{"LOCATION_NOTE_MONSTER25", "Shroom: Armada Interior - Rain Entryway 4"},
{"LOCATION_NOTE_MONSTER26", "Shroom: Armada Interior - Rain Entryway 3"},
{"LOCATION_NOTE_MONSTER27", "Shroom: Armada Interior - Rain Entryway 2"},
{"LOCATION_NOTE_MONSTER28", "Shroom: Armada Interior - Hammocks Entryway 2"},
{"LOCATION_NOTE_MONSTER29", "Shroom: Armada Interior - Hammocks Entryway 1"},
{"LOCATION_NOTE_MONSTER30", "Shroom: Armada Interior - Cockpit Entry 3"},
{"LOCATION_NOTE_MONSTER31", "Shroom: Armada Interior - Cockpit Entry 2"},
{"LOCATION_NOTE_MONSTER32", "Shroom: Armada Interior - Cockpit Entry 1"},
{"LOCATION_NOTE_MONSTER33", "Shroom: Armada Interior - Cockpit Entry 6"},
{"LOCATION_NOTE_MONSTER34", "Shroom: Armada Interior - Cockpit Entry 5"},
{"LOCATION_NOTE_MONSTER35", "Shroom: Armada Interior - Cockpit Entry 4"},
{"LOCATION_NOTE_MONSTER36", "Shroom: Armada Interior - Rain Below Medicine 3"},
{"LOCATION_NOTE_MONSTER37", "Shroom: Armada Interior - Rain Below Medicine 2"},
{"LOCATION_NOTE_MONSTER38", "Shroom: Armada Interior - Rain Below Boiler 1"},
{"LOCATION_NOTE_MONSTER39", "Shroom: Armada Interior - Rain Below Boiler 2"},
{"LOCATION_NOTE_MONSTER40", "Shroom: Armada Interior - Rain Below Boiler 3"},
{"LOCATION_NOTE_MONSTER41", "Shroom: Armada Interior - Rain Below Medicine 1"},
{"LOCATION_NOTE_MONSTER42", "Shroom: Armada Interior - Rain Plant Base"},
{"LOCATION_NOTE_MONSTER43", "Shroom: Armada Interior - Rain Plant 1"},
{"LOCATION_NOTE_MONSTER44", "Shroom: Armada Interior - Lab Rain Connector 5"},
{"LOCATION_NOTE_MONSTER45", "Shroom: Armada Interior - Lab Rain Connector 6"},
{"LOCATION_NOTE_MONSTER46", "Shroom: Armada Interior - Lab Rain Connector 4"},
{"LOCATION_NOTE_MONSTER47", "Shroom: Armada Interior - Lab Rain Connector 3"},
{"LOCATION_NOTE_MONSTER48", "Shroom: Armada Interior - Lab Rain Connector 2"},
{"LOCATION_NOTE_MONSTER49", "Shroom: Armada Interior - Lab Rain Connector 1"},
{"LOCATION_NOTE_MONSTER50", "Shroom: Armada Interior - Lab Entryway 4"},
{"LOCATION_NOTE_MONSTER51", "Shroom: Armada Interior - Lab Entryway 3"},
{"LOCATION_NOTE_MONSTER52", "Shroom: Armada Interior - Lab Entryway 2"},
{"LOCATION_NOTE_MONSTER53", "Shroom: Armada Interior - Lab Entryway 1"},
{"LOCATION_NOTE_MONSTER54", "Shroom: Armada Interior - Pipe 5"},
{"LOCATION_NOTE_MONSTER55", "Shroom: Armada Interior - Pipe 4"},
{"LOCATION_NOTE_MONSTER56", "Shroom: Armada Interior - Pipe 3"},
{"LOCATION_NOTE_MONSTER57", "Shroom: Armada Interior - Pipe 2"},
{"LOCATION_NOTE_MONSTER58", "Shroom: Armada Interior - Pipe 1"},
{"LOCATION_NOTE_MONSTER59", "Shroom: Armada Interior - Pipe Ramp 3"},
{"LOCATION_NOTE_MONSTER60", "Shroom: Armada Interior - Pipe Ramp 2"},
{"LOCATION_NOTE_MONSTER61", "Shroom: Armada Interior - Pipe Ramp 1"},
{"LOCATION_NOTE_MONSTER62", "Shroom: Armada Interior - Rain Entryway 1"},
{"LOCATION_NOTE_MONSTER63", "Shroom: Armada Interior - Slide Entryway 1"},
{"LOCATION_NOTE_MONSTER64", "Shroom: Armada Interior - Slide Entryway 2"},
{"LOCATION_NOTE_MONSTER65", "Shroom: Armada Interior - Slide Entryway 3"},
{"LOCATION_NOTE_MONSTER66", "Shroom: Armada Interior - Rain Plant 2"},
{"LOCATION_NOTE_MONSTER67", "Shroom: Armada Interior - Rain Plant 3"},
{"LOCATION_NOTE_MONSTER68", "Shroom: Armada Interior - Rain Plant 4"},
{"LOCATION_NOTE_MONSTER69", "Shroom: Armada Interior - Rain Above Boiler 4"},
{"LOCATION_NOTE_MONSTER70", "Shroom: Armada Interior - Rain Above Boiler 2"},
{"LOCATION_NOTE_MONSTER71", "Shroom: Armada Interior - Rain Above Boiler 1"},
{"LOCATION_NOTE_MONSTER72", "Shroom: Armada Interior - Rain Above Boiler 3"},
{"LOCATION_NOTE_MONSTER73", "Shroom: Armada Entry Drone - Ledges 6"},
{"LOCATION_NOTE_MONSTER74", "Shroom: Armada Entry Drone - Ledges 5"},
{"LOCATION_NOTE_MONSTER75", "Shroom: Armada Entry Drone - Ledges 4"},
{"LOCATION_NOTE_MONSTER76", "Shroom: Armada Entry Drone - Ledges 3"},
{"LOCATION_NOTE_MONSTER77", "Shroom: Armada Entry Drone - Ledges 7"},
{"LOCATION_NOTE_MONSTER78", "Shroom: Armada Entry Drone - Ledges 8"},
{"LOCATION_NOTE_MONSTER79", "Shroom: Armada Entry Drone - Ledges 1"},
{"LOCATION_NOTE_MONSTER80", "Shroom: Armada Entry Drone - Ledges 2"},
{"LOCATION_NOTE_PALACE1", "Shroom: Prismic Palace - Poms 5"},
{"LOCATION_NOTE_PALACE2", "Shroom: Prismic Palace - Poms 3"},
{"LOCATION_NOTE_PALACE3", "Shroom: Prismic Palace - Poms 4"},
{"LOCATION_NOTE_PALACE4", "Shroom: Prismic Palace - Poms 2"},
{"LOCATION_NOTE_PALACE5", "Shroom: Prismic Palace - Poms 1"},
{"LOCATION_NOTE_PALACE6", "Shroom: Prismic Palace - Entry Tree 2"},
{"LOCATION_NOTE_PALACE7", "Shroom: Prismic Palace - Entry Tree 1"},
{"LOCATION_NOTE_PALACE8", "Shroom: Prismic Palace - Entry Tree 3"},
{"LOCATION_NOTE_PALACE9", "Shroom: Prismic Palace - Entry 1"},
{"LOCATION_NOTE_PALACE10", "Shroom: Prismic Palace - Entry 2"},
{"LOCATION_NOTE_PALACE11", "Shroom: Prismic Palace - Entry 3"},
{"LOCATION_NOTE_PALACE12", "Shroom: Prismic Palace - Jester Boots 1"},
{"LOCATION_NOTE_PALACE13", "Shroom: Prismic Palace - Jester Boots 2"},
{"LOCATION_NOTE_PALACE14", "Shroom: Prismic Palace - Jester Boots 3"},
{"LOCATION_NOTE_PALACE15", "Shroom: Prismic Palace - Jester Boots 4"},
{"LOCATION_NOTE_PALACE16", "Shroom: Prismic Palace - Jester Boots 5"},
{"LOCATION_NOTE_PALACE17", "Shroom: Prismic Palace - Pom Spire 1"},
{"LOCATION_NOTE_PALACE18", "Shroom: Prismic Palace - Pom Spire 2"},
{"LOCATION_NOTE_PALACE19", "Shroom: Prismic Palace - Pom Spire 3"},
{"LOCATION_NOTE_PALACE20", "Shroom: Prismic Palace - Pom Spire 4"},
{"LOCATION_NOTE_PALACE21", "Shroom: Prismic Palace - Pom Spire 5"},
{"LOCATION_NOTE_PALACE22", "Shroom: Prismic Palace - Observatory Spire 1"},
{"LOCATION_NOTE_PALACE23", "Shroom: Prismic Palace - Observatory Spire 2"},
{"LOCATION_NOTE_PALACE24", "Shroom: Prismic Palace - Observatory Spire 3"},
{"LOCATION_NOTE_PALACE25", "Shroom: Prismic Palace - Observatory Spire 4"},
{"LOCATION_NOTE_PALACE26", "Shroom: Prismic Palace - Observatory Spire 5"},
{"LOCATION_NOTE_PALACE27", "Shroom: Prismic Palace - Lake Gobbler 2"},
{"LOCATION_NOTE_PALACE28", "Shroom: Prismic Palace - Lake Gobbler 3"},
{"LOCATION_NOTE_PALACE29", "Shroom: Prismic Palace - Lake Gobbler 1"},
{"LOCATION_NOTE_PALACE30", "Shroom: Prismic Palace - Lake Plants 2"},
{"LOCATION_NOTE_PALACE31", "Shroom: Prismic Palace - Lake Plants 3"},
{"LOCATION_NOTE_PALACE32", "Shroom: Prismic Palace - Lake Plants 1"},
{"LOCATION_NOTE_PALACE33", "Shroom: Prismic Palace - Lake Plants 5"},
{"LOCATION_NOTE_PALACE34", "Shroom: Prismic Palace - Lake Plants 6"},
{"LOCATION_NOTE_PALACE35", "Shroom: Prismic Palace - Lake Plants 4"},
{"LOCATION_NOTE_PALACE36", "Shroom: Prismic Palace - Lake Basement Overpass 3"},
{"LOCATION_NOTE_PALACE37", "Shroom: Prismic Palace - Lake Basement Overpass 4"},
{"LOCATION_NOTE_PALACE38", "Shroom: Prismic Palace - Lake Basement Overpass 5"},
{"LOCATION_NOTE_PALACE39", "Shroom: Prismic Palace - Lake Basement Overpass 2"},
{"LOCATION_NOTE_PALACE40", "Shroom: Prismic Palace - Lake Basement Overpass 1"},
{"LOCATION_NOTE_PALACE41", "Shroom: Prismic Palace - Lake Mushroom Cave 3"},
{"LOCATION_NOTE_PALACE42", "Shroom: Prismic Palace - Lake Mushroom Cave 4"},
{"LOCATION_NOTE_PALACE43", "Shroom: Prismic Palace - Lake Mushroom Cave 5"},
{"LOCATION_NOTE_PALACE44", "Shroom: Prismic Palace - Lake Mushroom Cave 2"},
{"LOCATION_NOTE_PALACE45", "Shroom: Prismic Palace - Lake Mushroom Cave 1"},
{"LOCATION_NOTE_PALACE46", "Shroom: Prismic Palace - Observatory Slide 5"},
{"LOCATION_NOTE_PALACE47", "Shroom: Prismic Palace - Observatory Slide 4"},
{"LOCATION_NOTE_PALACE48", "Shroom: Prismic Palace - Observatory Slide 3"},
{"LOCATION_NOTE_PALACE49", "Shroom: Prismic Palace - Observatory Slide 2"},
{"LOCATION_NOTE_PALACE50", "Shroom: Prismic Palace - Observatory Slide 1"},
{"LOCATION_NOTE_PALACE51", "Shroom: Prismic Palace - Poki-Poki Cave 1"},
{"LOCATION_NOTE_PALACE52", "Shroom: Prismic Palace - Poki-Poki Cave 2"},
{"LOCATION_NOTE_PALACE53", "Shroom: Prismic Palace - Poki-Poki Cave 3"},
{"LOCATION_NOTE_PALACE54", "Shroom: Prismic Palace - Poki-Poki Cave 4"},
{"LOCATION_NOTE_PALACE55", "Shroom: Prismic Palace - Poki-Poki Cave 5"},
{"LOCATION_NOTE_PALACE56", "Shroom: Prismic Palace - Pool 1"},
{"LOCATION_NOTE_PALACE57", "Shroom: Prismic Palace - Pool 2"},
{"LOCATION_NOTE_PALACE58", "Shroom: Prismic Palace - Pool 3"},
{"LOCATION_NOTE_PALACE59", "Shroom: Prismic Palace - Pool 4"},
{"LOCATION_NOTE_PALACE60", "Shroom: Prismic Palace - Pool 5"},
{"LOCATION_NOTE_PALACE61", "Shroom: Prismic Palace - Lake Basement Entry 3"},
{"LOCATION_NOTE_PALACE62", "Shroom: Prismic Palace - Lake Basement Entry 4"},
{"LOCATION_NOTE_PALACE63", "Shroom: Prismic Palace - Lake Basement Entry 5"},
{"LOCATION_NOTE_PALACE64", "Shroom: Prismic Palace - Lake Basement Entry 6"},
{"LOCATION_NOTE_PALACE65", "Shroom: Prismic Palace - Lake Basement Entry 8"},
{"LOCATION_NOTE_PALACE66", "Shroom: Prismic Palace - Lake Basement Entry 7"},
{"LOCATION_NOTE_PALACE67", "Shroom: Prismic Palace - Lake Basement Entry 2"},
{"LOCATION_NOTE_PALACE68", "Shroom: Prismic Palace - Lake Basement Entry 1"},
{"LOCATION_NOTE_PALACE69", "Shroom: Prismic Palace - Lake Corner 1"},
{"LOCATION_NOTE_PALACE70", "Shroom: Prismic Palace - Lake Corner 2"},
{"LOCATION_NOTE_PALACE71", "Shroom: Prismic Palace - Lake Corner 3"},
{"LOCATION_NOTE_PALACE72", "Shroom: Prismic Palace - Lake Behind 3"},
{"LOCATION_NOTE_PALACE73", "Shroom: Prismic Palace - Lake Behind 1"},
{"LOCATION_NOTE_PALACE74", "Shroom: Prismic Palace - Lake Behind 2"},
{"LOCATION_NOTE_PALACE75", "Shroom: Prismic Palace - Pool Bridges 2"},
{"LOCATION_NOTE_PALACE76", "Shroom: Prismic Palace - Pool Bridges 3"},
{"LOCATION_NOTE_PALACE77", "Shroom: Prismic Palace - Pool Bridges 1"},
{"LOCATION_NOTE_PALACE78", "Shroom: Prismic Palace - Pool Bridges 5"},
{"LOCATION_NOTE_PALACE79", "Shroom: Prismic Palace - Pool Bridges 4"},
{"LOCATION_NOTE_PALACE80", "Shroom: Prismic Palace - Pool Bridges 6"},
{"LOCATION_NOTE_PALACE81", "Shroom: Palace Interior - Star Puzzle 3"},
{"LOCATION_NOTE_PALACE82", "Shroom: Palace Interior - Star Puzzle 1"},
{"LOCATION_NOTE_PALACE83", "Shroom: Palace Interior - Star Puzzle 2"},
{"LOCATION_NOTE_PALACE84", "Shroom: Palace Interior - Heaven's Path Entry 3"},
{"LOCATION_NOTE_PALACE85", "Shroom: Palace Interior - Heaven's Path Entry 1"},
{"LOCATION_NOTE_PALACE86", "Shroom: Palace Interior - Heaven's Path Entry 2"},
{"LOCATION_NOTE_PALACE87", "Shroom: Palace Interior - Bubble Conch Room 3"},
{"LOCATION_NOTE_PALACE88", "Shroom: Palace Interior - Bubble Conch Room 1"},
{"LOCATION_NOTE_PALACE89", "Shroom: Palace Interior - Bubble Conch Room 2"},
{"LOCATION_NOTE_PALACE90", "Shroom: Palace Interior - Sentry Control Chamber 3"},
{"LOCATION_NOTE_PALACE91", "Shroom: Palace Interior - Sentry Control Chamber 1"},
{"LOCATION_NOTE_PALACE92", "Shroom: Palace Interior - Sentry Control Chamber 2"},
{"LOCATION_NOTE_PALACE93", "Shroom: Palace Interior - Palace Back 1"},
{"LOCATION_NOTE_PALACE94", "Shroom: Palace Interior - Palace Back 2"},
{"LOCATION_NOTE_PALACE95", "Shroom: Palace Interior - Palace Back 3"},
{"LOCATION_NOTE_PALACE96", "Shroom: Palace Interior - Palace Back 4"},
{"LOCATION_NOTE_PALACE97", "Shroom: Palace Interior - Palace Back 5"},
{"LOCATION_NOTE_PALACE98", "Shroom: Palace Interior - Palace Back 6"},
{"LOCATION_NOTE_PALACE99", "Shroom: Palace Interior - Bubble Conch Room 4"},
{"LOCATION_NOTE_PALACE100", "Shroom: Palace Interior - Bubble Conch Room 5"},
};
public static readonly Dictionary<string, string> pickupItems = new(){
{"ITEM_FISH_FOOD", "Fish Food"},
{"ITEM_PRINCESS_1", "Lady Opal's Egg 1"},
{"ITEM_PRINCESS_2", "Lady Opal's Egg 2"},
{"ITEM_PRINCESS_3", "Lady Opal's Egg 3"},
};
public static readonly Dictionary<string, string> eventItems = new(){
{"CAVE_NURIKABE_FALLEN", "Mighty Wall Toppled"},
{"GRATITUDE_DOOR1", "Open Moon Cavern Heart Door"},
{"MONSTER_LOBBY_PIPES_RISEN", "Armada Lobby Pipes Risen"},
{"MONSTER_LOBBY_STEAM", "Armada Lobby Red Pipe Updraft"},
{"PALACE_LOBBY_FAUCET_ON", "Prismic Palace Lobby Faucet Running"},
{"CAVE_GALLERY_LOBBY_TORCH_EXTINGUISH", "Open Gallery Hedge Maze"},
{"LAKE_SWINGS_RAISED", "Raise Lake Swings"},
{"LAKE_KAPPA_SUCCESS", "Open Deep Woods"},
{"LAKE_CRYPT_GATE_OPEN", "Open Crypt"},
{"LAKE_BELL_RANG", "Open Church"},
{"LAKE_CHURCH_SUCCESS", "Open Church Egg"},
{"MONSTER_BOILS_REMOVED", "Open Armada Cockpit"},
{"PALACE_ABYSS_HOOP_SUCCESS", "Open Prismic Palace Basement"},
{"PALACE_LAKE_GATE_OPEN", "Open Prismic-Lostleaf Connector"},
{"PALACE_GATE_RISEN", "Open Prismic Palace Gate"},
{"PALACE_MELTED_ICE", "Unfreeze Prismic Palace"},
{"PALACE_SENTRIES_DISABLED", "Disable Prismic Palace Seedragons"},
{"PALACE_SANCTUM_RACE_FINISHED", "Open Heaven's Path Exit"},
{"GALLERY_SAGE_PAINTING_SUCCESS", "Open Gallery Doors"},
{"GALLERY_MONSTER_PAINTING_SUCCESS", "Open Mr. Kerrington Painting Gate"},
{"GALLERY_KAPPA_PAINTING_SUCCESS", "Open Skull's Diamond Eye"},
{"GALLERY_MONSTER_SHORTCUT_OPEN", "Open Gallery-Armada Connector"},
{"GALLERY_STATUE_PUZZLE_SUCCESS", "Open Gallery of Nightmares Swamp Door"},
{"GALLERY_ANGEL_STATUE_SHADOWS_SUCCESS", "Open Gallery of Nightmares Sewer Chest #1"},
{"GALLERY_PRINCESS_PAINTING_SUCCESS", "Open Gallery of Nightmares Sewer Chest #2"},
};
public static readonly Dictionary<string, string> cardItems = new(){
{"CARD_CAVE_MUSHROOM", "Card: Shroom"},
{"CARD_CAVE_NURIKABE", "Card: Mighty Wall"},
{"CARD_CAVE_KOI_CAVE", "Card: Pale Carpy"},
{"CARD_CAVE_SWITCH", "Card: Preston"},
{"CARD_CAVE_SHOOTING_STAR", "Card: Keehee"},
{"CARD_CAVE_HUNGER", "Card: Hunger"},
{"CARD_LAKE_KAPPA", "Card: Shelnert"},
{"CARD_LAKE_CRYPT", "Card: Shelwart"},
{"CARD_LAKE_KOI", "Card: Carpy"},
{"CARD_LAKE_SUN", "Card: Raay"},
{"CARD_LAKE_SAPLING", "Card: Sappleing"},
{"CARD_LAKE_GROVE", "Card: Gabby Grove"},
{"CARD_MONSTER_MONSTER", "Card: Mr. Kerrington"},
{"CARD_MONSTER_SPIN_BLADE", "Card: Skritch"},
{"CARD_MONSTER_BOIL", "Card: Boiby"},
{"CARD_MONSTER_DUMPLING", "Card: Dumpling"},
{"CARD_MONSTER_FISH", "Card: F.I.S.H"},
{"CARD_MONSTER_FF", "Card: Reaper"},
{"CARD_PALACE_PRINCESS", "Card: Lady Opal"},
{"CARD_PALACE_URCHIN", "Card: Poki-Poki"},
{"CARD_PALACE_PALM_TREE_FLOAT", "Card: Pom"},
{"CARD_PALACE_SEASTAR", "Card: Bigstar"},
{"CARD_PALACE_MORAY", "Card: The Gobbler!"},
{"CARD_PALACE_SENTRY", "Card: Seedragon"},
{"CARD_GALLERY_RATTLES", "Card: Rattles"},
{"CARD_GALLERY_GIANT", "Card: Sniffles"},
{"CARD_GALLERY_MIMIC_PAINTING", "Card: Starving Art"},
{"CARD_GALLERY_UNDEAD", "Card: Eternal"},
{"CARD_GALLERY_FIRE_SNAKE", "Card: Heartburn"},
{"CARD_GALLERY_CHOMP", "Card: Hawhaw"},
{"CARD_CAVE_DRAGON", "Card: Fynn"},
{"CARD_CAVE_FELLA", "Card: Fynn's Siblings"},
{"CARD_CAVE_SAGE", "Card: Sage"},
{"CARD_CAVE_VILLAIN", "Card: Luna"},
{"CARD_CAVE_PANDORA", "Card: Boxed Nightmare"},
{"CARD_CAVE_KING", "Card: Frozen King"},
};
public static readonly Dictionary<string, string> eggItems = new(){
{"FELLA_CAVE1", "Sun Egg"},
{"FELLA_CAVE2", "Green Starry Egg"},
{"FELLA_CAVE3", "Blue Moon Egg"},
{"FELLA_CAVE4", "Blorange Striped Egg"},
{"FELLA_CAVE5", "Blue Dotted Egg"},
{"FELLA_CAVE6", "American Egg"},
{"FELLA_CAVE7", "Red Swirly Egg"},
{"FELLA_CAVE8", "Ghost Egg"},
{"FELLA_LAKE1", "Hatchable Egg: Lostleaf Lake"},
{"FELLA_LAKE2", "Easter Zig-zag Egg"},
{"FELLA_LAKE3", "Apple Egg"},
{"FELLA_LAKE4", "Snowfall Egg"},
{"FELLA_LAKE5", "Fishbones Egg"},
{"FELLA_LAKE6", "Sunshine Egg"},
{"FELLA_LAKE7", "Birds Egg"},
{"FELLA_LAKE8", "Stained Glass Egg"},
{"FELLA_MONSTER1", "Hatchable Egg: Airborne Armada"},
{"FELLA_MONSTER2", "Burning Egg"},
{"FELLA_MONSTER3", "Bat Egg"},
{"FELLA_MONSTER4", "Doggy Egg"},
{"FELLA_MONSTER5", "Spooky Egg"},
{"FELLA_MONSTER6", "Smiley Egg"},
{"FELLA_MONSTER7", "Heart Egg"},
{"FELLA_MONSTER8", "Dumpling Egg"},
{"FELLA_PALACE1", "Hatchable Egg: Prismic Palace"},
{"FELLA_PALACE2", "Ornate Egg"},
{"FELLA_PALACE3", "Starlit Egg"},
{"FELLA_PALACE4", "Checkered Egg"},
{"FELLA_PALACE5", "Flower Egg"},
{"FELLA_PALACE6", "Snowstorm Egg"},
{"FELLA_PALACE7", "Zig-zag Egg"},
{"FELLA_PALACE8", "Happy Egg"},
{"FELLA_CHALICE1", "Red Eyes Egg"},
{"FELLA_DROWN1", "Seaweed Egg"},
{"FELLA_UNDEAD1", "Moonlight Egg"},
{"FELLA_GALLERY1", "Hatchable Egg: Gallery of Nightmares"},
{"FELLA_GALLERY2", "Ripped Egg"},
{"FELLA_GALLERY3", "Robot Egg"},
{"FELLA_GALLERY4", "Bricked Egg"},
{"FELLA_GALLERY5", "Ghost Egg"},
};
public static readonly Dictionary<string, string> shroomItems = new(){
{"NOTE_CAVE2", "Shroom"},
{"NOTE_CAVE3", "Shroom"},
{"NOTE_CAVE4", "Shroom"},
{"NOTE_CAVE5", "Shroom"},
{"NOTE_CAVE1", "Shroom"},
{"NOTE_CAVE6", "Shroom"},
{"NOTE_CAVE7", "Shroom"},
{"NOTE_CAVE8", "Shroom"},
{"NOTE_CAVE9", "Shroom"},
{"NOTE_CAVE10", "Shroom"},
{"NOTE_CAVE11", "Shroom"},
{"NOTE_CAVE12", "Shroom"},
{"NOTE_CAVE13", "Shroom"},
{"NOTE_CAVE14", "Shroom"},
{"NOTE_CAVE15", "Shroom"},
{"NOTE_CAVE16", "Shroom"},
{"NOTE_CAVE17", "Shroom"},
{"NOTE_CAVE18", "Shroom"},
{"NOTE_CAVE19", "Shroom"},
{"NOTE_CAVE20", "Shroom"},
{"NOTE_CAVE21", "Shroom"},
{"NOTE_CAVE22", "Shroom"},
{"NOTE_CAVE23", "Shroom"},
{"NOTE_CAVE24", "Shroom"},
{"NOTE_CAVE25", "Shroom"},
{"NOTE_CAVE26", "Shroom"},
{"NOTE_CAVE27", "Shroom"},
{"NOTE_CAVE28", "Shroom"},
{"NOTE_CAVE29", "Shroom"},
{"NOTE_CAVE30", "Shroom"},
{"NOTE_CAVE31", "Shroom"},
{"NOTE_CAVE32", "Shroom"},
{"NOTE_CAVE33", "Shroom"},
{"NOTE_CAVE34", "Shroom"},
{"NOTE_CAVE35", "Shroom"},
{"NOTE_CAVE36", "Shroom"},
{"NOTE_CAVE37", "Shroom"},
{"NOTE_CAVE38", "Shroom"},
{"NOTE_CAVE39", "Shroom"},
{"NOTE_CAVE40", "Shroom"},
{"NOTE_CAVE41", "Shroom"},
{"NOTE_CAVE42", "Shroom"},
{"NOTE_CAVE43", "Shroom"},
{"NOTE_CAVE44", "Shroom"},
{"NOTE_CAVE45", "Shroom"},
{"NOTE_CAVE46", "Shroom"},
{"NOTE_CAVE47", "Shroom"},
{"NOTE_CAVE48", "Shroom"},
{"NOTE_CAVE49", "Shroom"},
{"NOTE_CAVE50", "Shroom"},
{"NOTE_CAVE51", "Shroom"},
{"NOTE_CAVE52", "Shroom"},
{"NOTE_CAVE53", "Shroom"},
{"NOTE_CAVE54", "Shroom"},
{"NOTE_CAVE55", "Shroom"},
{"NOTE_CAVE56", "Shroom"},
{"NOTE_CAVE57", "Shroom"},
{"NOTE_CAVE58", "Shroom"},
{"NOTE_CAVE59", "Shroom"},
{"NOTE_CAVE60", "Shroom"},
{"NOTE_CAVE61", "Shroom"},
{"NOTE_CAVE62", "Shroom"},
{"NOTE_CAVE63", "Shroom"},
{"NOTE_CAVE64", "Shroom"},
{"NOTE_CAVE65", "Shroom"},
{"NOTE_CAVE66", "Shroom"},
{"NOTE_CAVE67", "Shroom"},
{"NOTE_CAVE68", "Shroom"},
{"NOTE_CAVE69", "Shroom"},
{"NOTE_CAVE70", "Shroom"},
{"NOTE_CAVE71", "Shroom"},
{"NOTE_CAVE72", "Shroom"},
{"NOTE_CAVE73", "Shroom"},
{"NOTE_CAVE74", "Shroom"},
{"NOTE_CAVE75", "Shroom"},
{"NOTE_CAVE76", "Shroom"},
{"NOTE_CAVE77", "Shroom"},
{"NOTE_CAVE78", "Shroom"},
{"NOTE_CAVE79", "Shroom"},
{"NOTE_CAVE80", "Shroom"},
{"NOTE_LAKE1", "Shroom"},
{"NOTE_LAKE2", "Shroom"},
{"NOTE_LAKE3", "Shroom"},
{"NOTE_LAKE4", "Shroom"},
{"NOTE_LAKE5", "Shroom"},
{"NOTE_LAKE6", "Shroom"},
{"NOTE_LAKE7", "Shroom"},
{"NOTE_LAKE8", "Shroom"},
{"NOTE_LAKE9", "Shroom"},
{"NOTE_LAKE10", "Shroom"},
{"NOTE_LAKE11", "Shroom"},
{"NOTE_LAKE12", "Shroom"},
{"NOTE_LAKE13", "Shroom"},
{"NOTE_LAKE14", "Shroom"},
{"NOTE_LAKE15", "Shroom"},
{"NOTE_LAKE16", "Shroom"},
{"NOTE_LAKE17", "Shroom"},
{"NOTE_LAKE18", "Shroom"},
{"NOTE_LAKE19", "Shroom"},
{"NOTE_LAKE20", "Shroom"},
{"NOTE_LAKE21", "Shroom"},
{"NOTE_LAKE22", "Shroom"},
{"NOTE_LAKE23", "Shroom"},
{"NOTE_LAKE24", "Shroom"},
{"NOTE_LAKE25", "Shroom"},
{"NOTE_LAKE26", "Shroom"},
{"NOTE_LAKE27", "Shroom"},
{"NOTE_LAKE28", "Shroom"},
{"NOTE_LAKE29", "Shroom"},
{"NOTE_LAKE30", "Shroom"},
{"NOTE_LAKE31", "Shroom"},
{"NOTE_LAKE32", "Shroom"},
{"NOTE_LAKE33", "Shroom"},
{"NOTE_LAKE34", "Shroom"},
{"NOTE_LAKE35", "Shroom"},
{"NOTE_LAKE36", "Shroom"},
{"NOTE_LAKE37", "Shroom"},
{"NOTE_LAKE38", "Shroom"},
{"NOTE_LAKE39", "Shroom"},
{"NOTE_LAKE40", "Shroom"},
{"NOTE_LAKE41", "Shroom"},
{"NOTE_LAKE42", "Shroom"},
{"NOTE_LAKE43", "Shroom"},
{"NOTE_LAKE44", "Shroom"},
{"NOTE_LAKE45", "Shroom"},
{"NOTE_LAKE46", "Shroom"},
{"NOTE_LAKE47", "Shroom"},
{"NOTE_LAKE48", "Shroom"},
{"NOTE_LAKE49", "Shroom"},
{"NOTE_LAKE50", "Shroom"},
{"NOTE_LAKE51", "Shroom"},
{"NOTE_LAKE52", "Shroom"},
{"NOTE_LAKE53", "Shroom"},
{"NOTE_LAKE54", "Shroom"},
{"NOTE_LAKE55", "Shroom"},
{"NOTE_LAKE56", "Shroom"},
{"NOTE_LAKE57", "Shroom"},
{"NOTE_LAKE58", "Shroom"},
{"NOTE_LAKE59", "Shroom"},
{"NOTE_LAKE60", "Shroom"},
{"NOTE_MONSTER1", "Shroom"},
{"NOTE_MONSTER2", "Shroom"},
{"NOTE_MONSTER3", "Shroom"},
{"NOTE_MONSTER4", "Shroom"},
{"NOTE_MONSTER5", "Shroom"},
{"NOTE_MONSTER6", "Shroom"},
{"NOTE_MONSTER7", "Shroom"},
{"NOTE_MONSTER8", "Shroom"},
{"NOTE_MONSTER9", "Shroom"},
{"NOTE_MONSTER10", "Shroom"},
{"NOTE_MONSTER11", "Shroom"},
{"NOTE_MONSTER12", "Shroom"},
{"NOTE_MONSTER13", "Shroom"},
{"NOTE_MONSTER14", "Shroom"},
{"NOTE_MONSTER15", "Shroom"},
{"NOTE_MONSTER16", "Shroom"},
{"NOTE_MONSTER17", "Shroom"},
{"NOTE_MONSTER18", "Shroom"},
{"NOTE_MONSTER19", "Shroom"},
{"NOTE_MONSTER20", "Shroom"},
{"NOTE_MONSTER21", "Shroom"},
{"NOTE_MONSTER22", "Shroom"},
{"NOTE_MONSTER23", "Shroom"},
{"NOTE_MONSTER24", "Shroom"},
{"NOTE_MONSTER25", "Shroom"},
{"NOTE_MONSTER26", "Shroom"},
{"NOTE_MONSTER27", "Shroom"},
{"NOTE_MONSTER28", "Shroom"},
{"NOTE_MONSTER29", "Shroom"},
{"NOTE_MONSTER30", "Shroom"},
{"NOTE_MONSTER31", "Shroom"},
{"NOTE_MONSTER32", "Shroom"},
{"NOTE_MONSTER33", "Shroom"},
{"NOTE_MONSTER34", "Shroom"},
{"NOTE_MONSTER35", "Shroom"},
{"NOTE_MONSTER36", "Shroom"},
{"NOTE_MONSTER37", "Shroom"},
{"NOTE_MONSTER38", "Shroom"},
{"NOTE_MONSTER39", "Shroom"},
{"NOTE_MONSTER40", "Shroom"},
{"NOTE_MONSTER41", "Shroom"},
{"NOTE_MONSTER42", "Shroom"},
{"NOTE_MONSTER43", "Shroom"},
{"NOTE_MONSTER44", "Shroom"},
{"NOTE_MONSTER45", "Shroom"},
{"NOTE_MONSTER46", "Shroom"},
{"NOTE_MONSTER47", "Shroom"},
{"NOTE_MONSTER48", "Shroom"},
{"NOTE_MONSTER49", "Shroom"},
{"NOTE_MONSTER50", "Shroom"},
{"NOTE_MONSTER51", "Shroom"},
{"NOTE_MONSTER52", "Shroom"},
{"NOTE_MONSTER53", "Shroom"},
{"NOTE_MONSTER54", "Shroom"},
{"NOTE_MONSTER55", "Shroom"},
{"NOTE_MONSTER56", "Shroom"},
{"NOTE_MONSTER57", "Shroom"},
{"NOTE_MONSTER58", "Shroom"},
{"NOTE_MONSTER59", "Shroom"},
{"NOTE_MONSTER60", "Shroom"},
{"NOTE_MONSTER61", "Shroom"},
{"NOTE_MONSTER62", "Shroom"},
{"NOTE_MONSTER63", "Shroom"},
{"NOTE_MONSTER64", "Shroom"},
{"NOTE_MONSTER65", "Shroom"},
{"NOTE_MONSTER66", "Shroom"},
{"NOTE_MONSTER67", "Shroom"},
{"NOTE_MONSTER68", "Shroom"},
{"NOTE_MONSTER69", "Shroom"},
{"NOTE_MONSTER70", "Shroom"},
{"NOTE_MONSTER71", "Shroom"},
{"NOTE_MONSTER72", "Shroom"},
{"NOTE_MONSTER73", "Shroom"},
{"NOTE_MONSTER74", "Shroom"},
{"NOTE_MONSTER75", "Shroom"},
{"NOTE_MONSTER76", "Shroom"},
{"NOTE_MONSTER77", "Shroom"},
{"NOTE_MONSTER78", "Shroom"},
{"NOTE_MONSTER79", "Shroom"},
{"NOTE_MONSTER80", "Shroom"},
{"NOTE_PALACE1", "Shroom"},
{"NOTE_PALACE2", "Shroom"},
{"NOTE_PALACE3", "Shroom"},
{"NOTE_PALACE4", "Shroom"},
{"NOTE_PALACE5", "Shroom"},
{"NOTE_PALACE6", "Shroom"},
{"NOTE_PALACE7", "Shroom"},
{"NOTE_PALACE8", "Shroom"},
{"NOTE_PALACE9", "Shroom"},
{"NOTE_PALACE10", "Shroom"},
{"NOTE_PALACE11", "Shroom"},
{"NOTE_PALACE12", "Shroom"},
{"NOTE_PALACE13", "Shroom"},
{"NOTE_PALACE14", "Shroom"},
{"NOTE_PALACE15", "Shroom"},
{"NOTE_PALACE16", "Shroom"},
{"NOTE_PALACE17", "Shroom"},
{"NOTE_PALACE18", "Shroom"},
{"NOTE_PALACE19", "Shroom"},
{"NOTE_PALACE20", "Shroom"},
{"NOTE_PALACE21", "Shroom"},
{"NOTE_PALACE22", "Shroom"},
{"NOTE_PALACE23", "Shroom"},
{"NOTE_PALACE24", "Shroom"},
{"NOTE_PALACE25", "Shroom"},
{"NOTE_PALACE26", "Shroom"},
{"NOTE_PALACE27", "Shroom"},
{"NOTE_PALACE28", "Shroom"},
{"NOTE_PALACE29", "Shroom"},
{"NOTE_PALACE30", "Shroom"},
{"NOTE_PALACE31", "Shroom"},
{"NOTE_PALACE32", "Shroom"},
{"NOTE_PALACE33", "Shroom"},
{"NOTE_PALACE34", "Shroom"},
{"NOTE_PALACE35", "Shroom"},
{"NOTE_PALACE36", "Shroom"},
{"NOTE_PALACE37", "Shroom"},
{"NOTE_PALACE38", "Shroom"},
{"NOTE_PALACE39", "Shroom"},
{"NOTE_PALACE40", "Shroom"},
{"NOTE_PALACE41", "Shroom"},
{"NOTE_PALACE42", "Shroom"},
{"NOTE_PALACE43", "Shroom"},
{"NOTE_PALACE44", "Shroom"},
{"NOTE_PALACE45", "Shroom"},
{"NOTE_PALACE46", "Shroom"},
{"NOTE_PALACE47", "Shroom"},
{"NOTE_PALACE48", "Shroom"},
{"NOTE_PALACE49", "Shroom"},
{"NOTE_PALACE50", "Shroom"},
{"NOTE_PALACE51", "Shroom"},
{"NOTE_PALACE52", "Shroom"},
{"NOTE_PALACE53", "Shroom"},
{"NOTE_PALACE54", "Shroom"},
{"NOTE_PALACE55", "Shroom"},
{"NOTE_PALACE56", "Shroom"},
{"NOTE_PALACE57", "Shroom"},
{"NOTE_PALACE58", "Shroom"},
{"NOTE_PALACE59", "Shroom"},
{"NOTE_PALACE60", "Shroom"},
{"NOTE_PALACE61", "Shroom"},
{"NOTE_PALACE62", "Shroom"},
{"NOTE_PALACE63", "Shroom"},
{"NOTE_PALACE64", "Shroom"},
{"NOTE_PALACE65", "Shroom"},
{"NOTE_PALACE66", "Shroom"},
{"NOTE_PALACE67", "Shroom"},
{"NOTE_PALACE68", "Shroom"},
{"NOTE_PALACE69", "Shroom"},
{"NOTE_PALACE70", "Shroom"},
{"NOTE_PALACE71", "Shroom"},
{"NOTE_PALACE72", "Shroom"},
{"NOTE_PALACE73", "Shroom"},
{"NOTE_PALACE74", "Shroom"},
{"NOTE_PALACE75", "Shroom"},
{"NOTE_PALACE76", "Shroom"},
{"NOTE_PALACE77", "Shroom"},
{"NOTE_PALACE78", "Shroom"},
{"NOTE_PALACE79", "Shroom"},
{"NOTE_PALACE80", "Shroom"},
{"NOTE_PALACE81", "Shroom"},
{"NOTE_PALACE82", "Shroom"},
{"NOTE_PALACE83", "Shroom"},
{"NOTE_PALACE84", "Shroom"},
{"NOTE_PALACE85", "Shroom"},
{"NOTE_PALACE86", "Shroom"},
{"NOTE_PALACE87", "Shroom"},
{"NOTE_PALACE88", "Shroom"},
{"NOTE_PALACE89", "Shroom"},
{"NOTE_PALACE90", "Shroom"},
{"NOTE_PALACE91", "Shroom"},
{"NOTE_PALACE92", "Shroom"},
{"NOTE_PALACE93", "Shroom"},
{"NOTE_PALACE94", "Shroom"},
{"NOTE_PALACE95", "Shroom"},
{"NOTE_PALACE96", "Shroom"},
{"NOTE_PALACE97", "Shroom"},
{"NOTE_PALACE98", "Shroom"},
{"NOTE_PALACE99", "Shroom"},
{"NOTE_PALACE100", "Shroom"},
};
}}